version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging into Amazon ECR.....
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - REPOSITORY_URI=285091344673.dkr.ecr.us-west-2.amazonaws.com/hack
        - chmod +x ./createRepositories.sh
        - ./createRepositories.sh
  build:
    commands:
      - echo Build started on `date`
      - echo Starting / Building the Docker images...
      - docker-compose up --build -d
  post_build:
    commands:
      - echo Persisting the data to artifact..
      - docker-compose stop
      - echo Pushing the Images..
      - docker-compose push

artifacts:
  files:
    - "**/*"
