version: "2"

services:
  api:
    build: ./api
    container_name: api
    ports:
      - "80:80"

#  webapp:
#    build: ./frontend
#    container_name: webapp
#    ports:
#      - "80:80"
#    links:
#      - api
